# Generated by Django 6.0.7 on 2026-07-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_number", models.IntegerField(help_text="Введите номер столика", verbose_name="Номер столика")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Введите описание столика", null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото столика",
                        null=True,
                        upload_to="data/image_table",
                        verbose_name="Фото столика",
                    ),
                ),
                (
                    "number_of_guests",
                    models.IntegerField(help_text="Укажите количество гостей", verbose_name="Количество гостей"),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["table_number"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("guests_name", models.CharField(help_text="Укажите ФИО", max_length=50, verbose_name="ФИО")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("phone", models.CharField(help_text="Укажите номер телефона", max_length=11, verbose_name="Телефон")),
                (
                    "booking_date",
                    models.DateTimeField(
                        help_text="Укажите когда вы хотите забронировать столик (день и время)",
                        verbose_name="Дата и время бронирования",
                    ),
                ),
                (
                    "number_of_guests",
                    models.IntegerField(help_text="Укажите количество гостей", verbose_name="Количество гостей"),
                ),
                (
                    "booking_end",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Автоматически рассчитывается как начало бронирования + 4 часа",
                        null=True,
                        verbose_name="Дата и время окончания бронирования",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Введите название категории",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="con_amore.table",
                        verbose_name="Столик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["table", "phone", "booking_date", "guests_name"],
            },
        ),
    ]
