# Generated by Django 6.0.7 on 2026-07-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_amore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.CharField(
                blank=True, help_text="Добавьте описание", max_length=200, null=True, verbose_name="Описание"
            ),
        ),
    ]
