# Generated by Django 6.0.7 on 2026-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_amore", "0002_alter_table_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
