# Generated by Django 6.0.7 on 2026-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("con_amore", "0003_alter_reservation_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "data_at",
                    models.CharField(
                        help_text="Добавьте дату создания фото", max_length=20, verbose_name="Дата создания фото"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото",
                        null=True,
                        upload_to="data/image_foto",
                        verbose_name="Фото ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Укажите свое имя", max_length=20, verbose_name="Автор")),
                (
                    "review",
                    models.CharField(
                        blank=True, help_text="Добавьте отзыв", max_length=200, null=True, verbose_name="Отзыв"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
    ]
